blank_issues_enabled: false
contact_links:
  - name: Suggest a new plugin
    url: https://feedback.squaredup.com/plugins
    about: New plugins can be suggested on our public feedback board, though anyone can build a new plugin - PRs welcome!
  - name: Report a bug or feature request with SquaredUp
    url: https://docs.squaredup.com/submit-ticket
    about: Please report issues with the SquaredUp platform via our support team.
  - name: Get help from the community
    url: https://community.squaredup.com
    about: Our Community Answers platform is great for getting help from members of the community.
